# -*- coding: utf-8 -*-
"""ObjectDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hj6P2BCF1z-eyLaGfuCSg2yXuwSrGIO9
"""

!pip install ultralytics opencv-python

from ultralytics import YOLO
import numpy as np
from PIL import Image

# pre-trained YOLOv8 model
model = YOLO("yolov8n.pt")

def detect_objects(image):
    image = np.array(image)
    results = model(image)

    # Extract objects
    detected_objects = []
    for result in results:
        for box in result.boxes:
            class_id = int(box.cls[0])
            confidence = float(box.conf[0])
            label = model.names[class_id]

            detected_objects.append(f"{label} ({confidence:.2f})")

    # output description
    if detected_objects:
        description = "Detected: " + ", ".join(detected_objects)
    else:
        description = "No objects detected."

    return results[0].plot(), description  # Gives us image with boxes and description

!pip install gradio

import gradio as gr

# User interface
iface = gr.Interface(
    fn=detect_objects,
    inputs=gr.Image(type="pil"),
    outputs=[gr.Image(type="numpy"), gr.Textbox()],
    title="AI Object Detection",
    description="Upload an image, and the model will detect objects and describe them."
)

# Launcing
iface.launch()

